<template>
    <div class="song_viewer">
        <p>Current value : {{scrollValue}}</p>
        <vue-slider ref="slider" v-model="scrollValue"></vue-slider>
        <vue-scrollbar classes="my-scrollbar" ref="Scrollbar">
            <div class="song_content">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sapien nunc, tristique nec nibh ac, dignissim pulvinar est. In tristique lorem tortor, vel vulputate nisl tempus in. Vestibulum a sapien magna. Duis gravida dictum ultricies. Nulla facilisi. Proin facilisis massa a commodo elementum. Nulla et aliquam leo, in bibendum mauris. Phasellus eu enim eget massa auctor posuere. Cras gravida ligula eget velit congue, vel facilisis justo eleifend.<br/>
                Donec auctor dapibus arcu, a laoreet massa tincidunt ut. Nulla ipsum tortor, egestas in urna id, efficitur aliquam lacus. Proin elit leo, euismod a gravida a, rhoncus nec augue. In mollis, nibh et luctus venenatis, elit odio faucibus sapien, eget scelerisque ligula neque aliquet lorem. Sed congue risus quis massa posuere porttitor. Etiam dictum egestas dictum. Nulla in sapien ut lorem pulvinar pretium. Curabitur nec lacinia augue. Nulla ut suscipit ipsum. Quisque bibendum euismod sagittis. Ut lobortis placerat turpis, quis semper libero ornare sed. Suspendisse suscipit pharetra ex, ut ullamcorper tellus. Integer ipsum elit, volutpat at lobortis ut, mattis id nulla. Suspendisse fringilla commodo erat, at vulputate ligula venenatis porttitor. Nunc dolor augue, pellentesque quis sapien nec, consequat dapibus tellus. Vestibulum in augue accumsan, fringilla justo quis, venenatis nulla.<br/>
                Aliquam eu quam congue, porttitor urna in, cursus odio. Nullam iaculis rutrum turpis, a posuere leo laoreet id. Ut vitae faucibus massa. Duis odio libero, posuere ac porta non, pretium in nunc. Nullam congue odio a nunc lacinia facilisis. In vestibulum tellus ac velit gravida fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius leo eget dui tempus pretium. Integer feugiat quam ex, non commodo ipsum tincidunt ac.<br/>
                Maecenas sollicitudin velit eget justo finibus tincidunt. Aenean et leo velit. Duis porta ornare dolor, nec sodales ipsum porttitor suscipit. Curabitur non justo nisi. Duis condimentum dolor nisl, non bibendum neque cursus vitae. Vivamus scelerisque enim sed odio pharetra, et gravida magna tincidunt. Proin tincidunt cursus nibh in suscipit. Morbi cursus ipsum ac ipsum dictum mattis. Fusce faucibus aliquet tellus, ut pulvinar ligula porttitor eu. Cras in condimentum felis. Nullam eu dapibus tortor. Aenean laoreet dictum tellus ut ultrices. Aliquam facilisis bibendum fermentum. Sed ut nibh eget velit mollis auctor at non massa.<br/>
                Aenean pellentesque at elit vel vestibulum. Fusce blandit eleifend arcu, non laoreet turpis ullamcorper ultricies. Mauris a magna suscipit, pellentesque ante sit amet, consectetur enim. Ut non varius lorem. Mauris euismod, libero a mollis dignissim, tellus ante semper erat, at varius augue odio non tellus. Fusce at vulputate risus. Duis tristique nulla et tortor vulputate, et lacinia nulla commodo. Sed sit amet tincidunt augue. Aenean et pellentesque justo. Nulla iaculis dictum ipsum quis bibendum. Nunc vehicula, risus eget placerat sollicitudin, mi dolor imperdiet tellus, non rutrum erat diam cursus elit. Vestibulum nunc libero, porttitor vel nibh sed, porta imperdiet risus. Phasellus eget mi ut erat blandit aliquet non nec dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam vulputate ante quis metus laoreet, eu semper quam tristique.<br/>
                Nunc pretium a ipsum ac mollis. Vestibulum sed scelerisque nunc. Morbi ornare, lectus quis ultricies mattis, libero libero finibus dui, eu fermentum dolor justo sed ante. Quisque hendrerit, leo non tincidunt auctor, dui sem pharetra magna, ac consequat neque sem sit amet ex. Vivamus in pharetra nisi, eget ultrices lectus. Sed suscipit laoreet ipsum. Nam volutpat urna quis nisl facilisis feugiat. Cras semper ipsum leo, ac efficitur tortor sagittis vitae. Curabitur tincidunt arcu sed condimentum euismod. Aenean eu ultricies lorem. Duis scelerisque placerat semper. Fusce eu dolor vitae purus congue aliquam.<br/>
                Praesent porta dolor et feugiat vehicula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas consequat feugiat mauris, vel semper purus lobortis efficitur. Pellentesque ut fringilla dui, non feugiat justo. In hac habitasse platea dictumst. Morbi non ultrices nisl. Donec ullamcorper placerat arcu, in vehicula est interdum sollicitudin. Fusce cursus ante vitae velit varius, quis interdum est interdum. Suspendisse cursus nunc id tellus tempus, sit amet tempus ipsum fringilla. Donec porttitor sit amet sapien eu dapibus. Aenean efficitur lorem eros, non pharetra ante euismod vitae. Nam in facilisis ipsum, ac luctus tellus. Nullam consectetur accumsan nulla, eu efficitur sem. Aenean ex arcu, efficitur quis lorem quis, luctus elementum libero. Curabitur rhoncus ultricies ultricies. Integer id eleifend libero.<br/>
                Cras tempus tortor eu dignissim pharetra. Fusce nec turpis dictum, fringilla tellus in, vehicula neque. Cras mollis nibh et ligula eleifend, a vestibulum augue lobortis. Sed vel lorem ac velit faucibus vehicula. Ut est orci, blandit at eros ut, venenatis pretium nunc. Etiam mollis eu odio nec pharetra. Curabitur hendrerit, elit et lacinia aliquam, arcu nibh elementum nunc, iaculis semper metus orci ac diam. Aliquam sed mauris mi. Vestibulum ipsum ante, vestibulum id leo ut, venenatis iaculis lacus. Fusce metus purus, convallis congue sapien non, ultrices lacinia lacus. Donec mattis volutpat velit sit amet venenatis. Curabitur faucibus tristique nunc, sed porta erat luctus quis. Vivamus laoreet ultrices pharetra. Nam dolor eros, tincidunt at consectetur non, accumsan quis leo. Curabitur aliquam ultricies eros, dictum pretium lacus tincidunt vitae.<br/>
                Sed tincidunt, ipsum quis feugiat ultricies, nunc lacus hendrerit ligula, vel pulvinar turpis massa at nisl. Etiam lobortis diam tempus mauris bibendum luctus. Ut gravida mattis metus ac convallis. Duis pellentesque velit diam, eget interdum lectus euismod at. Proin commodo convallis pulvinar. Pellentesque a justo in augue imperdiet porta scelerisque porta enim. Nulla ac bibendum quam, ultrices mollis diam. Phasellus sem eros, condimentum vel iaculis a, accumsan in quam.<br/>
                Sed ullamcorper, eros id sodales semper, mi justo posuere ante, venenatis interdum lacus felis ac eros. Aenean in volutpat urna. Proin vel dui at nunc pharetra ultrices ac eu eros. Mauris eu tortor eros. Mauris non porta erat. Curabitur dictum auctor dolor, non auctor felis vulputate nec. Maecenas in arcu quis sem pharetra pulvinar.<br/>
                Sed venenatis aliquam eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum pretium, nisi a egestas condimentum, ligula nulla aliquet augue, sed vulputate urna massa a enim. Sed est risus, pellentesque ac neque sed, pharetra interdum ex. Duis ullamcorper dui in ante facilisis vulputate. Proin ultricies finibus nisi quis rutrum. Donec leo mi, semper in gravida sit amet, tempus eu felis. Donec imperdiet imperdiet malesuada. In tincidunt lacus est, vel sodales elit malesuada id. Donec quis pellentesque sapien.<br/>
                Nullam eu condimentum nisl. Praesent a lectus in ipsum convallis ornare vulputate vel quam. Duis consectetur, urna quis porta ullamcorper, justo arcu congue sapien, gravida pharetra velit purus vel felis. Suspendisse rhoncus euismod viverra. Fusce fermentum ligula et interdum accumsan. Pellentesque at pulvinar tortor. Mauris at tellus tempor, mattis nunc vitae, gravida velit. Nulla fringilla a turpis vel vulputate. Donec fermentum enim id risus condimentum facilisis. Curabitur faucibus ex et elit vehicula finibus. Vivamus vel ante felis. Sed cursus libero eu diam venenatis scelerisque. Praesent dapibus porttitor ex in eleifend. Morbi eleifend ultricies erat, consectetur vestibulum nisl luctus et. Proin suscipit pellentesque nisl, eu aliquet nulla finibus nec.<br/>
                Etiam sit amet neque nec mi luctus auctor. Morbi convallis libero et lorem convallis condimentum. Aenean elit odio, mollis non dolor sed, pretium hendrerit augue. Nulla facilisi. Etiam ac scelerisque ligula, in dapibus massa. Sed pharetra justo eget augue tristique pulvinar. Praesent laoreet risus vel pellentesque efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed at dignissim nisi. Vestibulum vulputate pellentesque lorem, lobortis ullamcorper sem aliquet in. Nam malesuada quam sit amet sagittis consequat. Morbi non sagittis nibh.<br/>
                Donec iaculis volutpat congue. Duis venenatis nisl ultricies convallis congue. Vestibulum porta quam eget est congue, ac auctor justo sagittis. Nunc pellentesque leo eget nibh pulvinar, a feugiat quam sollicitudin. Vestibulum vestibulum lorem eget semper pellentesque. Quisque aliquam erat nec elementum lobortis. Vivamus pellentesque laoreet velit, a condimentum nunc maximus et.<br/>
                Aenean ut sodales ex. Morbi tristique semper sapien et convallis. Donec ultricies sollicitudin ullamcorper. Praesent justo erat, tincidunt quis libero vel, rhoncus aliquam metus. Aenean nec tempor mauris, eget luctus ligula. Quisque euismod laoreet ligula sit amet porttitor. Suspendisse laoreet orci ut erat aliquet ornare. Mauris tristique malesuada semper. Vivamus non nisl eros. Morbi purus lacus, finibus non nunc quis, malesuada iaculis dolor. Aliquam imperdiet arcu sed vulputate eleifend.<br/>
                Donec eu accumsan magna. Fusce gravida tellus at faucibus tincidunt. Integer ac velit venenatis turpis semper blandit sit amet id massa. In iaculis pellentesque libero, sit amet dictum augue imperdiet ut. Maecenas vel tellus id erat consequat scelerisque vitae quis felis. Fusce porta mollis nisi. Aliquam rutrum est sed vulputate tempor. Duis sed mattis velit. Quisque eu ipsum metus. Nunc sed porta risus, eu imperdiet dolor. Integer vel scelerisque tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur eu aliquam mauris.<br/>
                Vestibulum orci lacus, maximus at nibh in, aliquet rutrum arcu. Nam commodo arcu velit, sed iaculis sapien scelerisque et. Ut ultrices ultricies dolor, ac accumsan nisl facilisis vitae. Etiam et ullamcorper nisi. Duis laoreet sem urna, sed vulputate libero sodales quis. Maecenas at risus diam. Etiam enim nunc, vehicula sed dignissim et, sodales vitae ex. Quisque ultricies, turpis at dictum tincidunt, justo leo condimentum enim, eu luctus ipsum nisl quis libero. Aliquam sed elementum eros. Curabitur sit amet leo quis arcu tincidunt aliquam eget a eros. Sed eget aliquet orci.<br/>
                Nullam vulputate interdum metus id iaculis. In at risus cursus, sollicitudin lectus vitae, sollicitudin arcu. Aliquam vitae ultrices tortor, a pulvinar felis. Etiam efficitur, justo quis consequat malesuada, ante justo consequat nisi, ut sodales ex metus id odio. Praesent volutpat vestibulum tincidunt. Duis id aliquam augue. Nunc aliquam neque sit amet ex tristique, eget venenatis est suscipit. Sed mollis malesuada sem sit amet aliquet. Curabitur dolor justo, vulputate vel tortor non, vehicula placerat dolor.<br/>
                Mauris ac odio venenatis urna ultrices condimentum. Quisque sit amet diam ex. Nullam rhoncus, erat nec blandit euismod, arcu eros ornare sapien, at ultrices ex lorem a enim. Ut eget sodales nisl. Vestibulum eros nunc, efficitur non elementum quis, pretium sit amet tortor. Phasellus libero quam, eleifend vel sapien vel, sagittis condimentum lacus. Phasellus euismod ante eget velit rutrum, id vestibulum augue dapibus. Quisque et ex venenatis, facilisis magna eget, dapibus arcu. Nam quis neque id nisl pretium volutpat. Sed scelerisque ipsum vel augue lobortis consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis tincidunt condimentum fermentum. Praesent scelerisque quam sed tortor pulvinar, non malesuada leo semper. Vestibulum rutrum ac felis et ullamcorper. Integer sollicitudin purus et massa interdum eleifend. Nulla ultricies diam sit amet eros congue volutpat.<br/>
                Nunc maximus massa ligula, id efficitur nisl consequat in. Donec velit ex, cursus vel diam id, malesuada vestibulum mauris. Proin eget leo in dolor venenatis egestas eget vel eros. Aenean in risus a enim vestibulum tempus. Duis et pretium dolor, vel varius eros. Nulla aliquet fringilla pulvinar. In eu lorem ut erat vestibulum aliquam in eget orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque lobortis, risus eget ullamcorper ultrices, metus tortor porta ex, ac cursus ligula felis quis velit. Phasellus neque nibh, accumsan at pulvinar ac, maximus vel dolor. Vivamus ornare placerat dolor sed volutpat. Nulla quis pulvinar est.<br/>
                Praesent ut justo mattis, consequat nisl id, ultrices mi. Pellentesque et tempor est. In hac habitasse platea dictumst. Proin at lobortis dolor, sed scelerisque nisl. Nam mollis enim libero, nec venenatis dui ultricies quis. Vestibulum placerat, tellus laoreet scelerisque imperdiet, nibh sem gravida lacus, sit amet tristique arcu odio et magna. Cras sit amet dictum diam, fermentum imperdiet massa. Aliquam cursus gravida est nec lobortis. Nulla facilisi. Donec sollicitudin tellus rutrum nunc fringilla, vitae convallis quam ultrices. Pellentesque magna est, dictum ac leo eget, hendrerit consequat arcu. Vivamus rhoncus dui sit amet nulla tristique, ut facilisis quam porta.<br/>
                Pellentesque at erat a dolor congue condimentum ac non magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi et vulputate odio. Phasellus cursus urna tellus, vehicula tincidunt orci vehicula id. Nunc pellentesque lobortis nulla, quis condimentum tortor ultrices non. Vestibulum egestas, elit quis dictum sodales, risus magna ornare nulla, quis iaculis turpis lectus et diam. Aenean placerat magna massa, tempor porta leo pretium non. Maecenas auctor in justo sed elementum. Suspendisse vel lorem ipsum. Duis a lectus tempor, luctus felis sed, porttitor mauris. Proin nec ipsum laoreet, commodo magna non, pretium enim. Duis non efficitur sem, viverra mattis odio. Quisque vel felis sit amet lectus tristique vestibulum nec eget eros.<br/>
                Aliquam porttitor iaculis rutrum. Maecenas tempor sem dolor, eu laoreet libero dictum eget. Nunc sollicitudin justo sit amet congue tincidunt. Nullam lacinia porttitor congue. Fusce semper pulvinar tortor, a semper urna pulvinar vel. Mauris egestas rutrum erat at imperdiet. Aenean vel enim eget orci hendrerit aliquam at eu arcu.<br/>
                Curabitur vitae ligula laoreet, tempus est quis, consectetur enim. Donec sodales nulla sed finibus congue. Nullam quis consequat sem. Suspendisse elementum eu nisl sed faucibus. Quisque aliquam pulvinar metus, a varius est iaculis et. Aenean sit amet condimentum nisi, eget condimentum dui. Praesent et mauris ex. Aenean sit amet urna orci. Integer eu convallis risus. Maecenas id urna molestie diam viverra sagittis sed ac nisl. Donec bibendum ultrices tellus ac luctus. Maecenas aliquet magna non nisl faucibus, non rhoncus ex tincidunt. Duis non rutrum eros, non porttitor arcu. Pellentesque et laoreet nisi.<br/>
                In vehicula faucibus diam a efficitur. Cras semper neque ac volutpat lobortis. Phasellus quis odio at urna aliquet sodales. Integer lacinia nunc nec tellus euismod vestibulum. Cras id nibh vitae tellus laoreet laoreet. Etiam mauris tortor, euismod nec orci sed, tempor accumsan leo. Aliquam dapibus enim ut massa auctor, vitae feugiat odio convallis. Nulla ante elit, euismod ac tristique in, hendrerit ac nisl. Fusce quis risus a dui vulputate facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean suscipit ipsum non euismod scelerisque. Proin enim ligula, euismod vehicula accumsan nec, aliquet non turpis.<br/>
                Duis id neque in dui mattis lobortis. Pellentesque tempus laoreet ex sed placerat. Curabitur volutpat tristique urna, a tincidunt massa auctor aliquet. Fusce consectetur posuere lacus in scelerisque. Sed vitae sapien at dui facilisis bibendum aliquet sed libero. Cras accumsan, diam ac ultrices rhoncus, leo enim vehicula diam, eget venenatis urna mi vitae sem. Morbi vel enim at ante ullamcorper suscipit ullamcorper nec eros. Nulla id magna vel metus volutpat elementum in vitae quam. Maecenas cursus magna nunc. Nullam a rhoncus orci, ac varius purus. Fusce sagittis iaculis sapien vehicula pulvinar. Nulla rhoncus dictum nisi ac pulvinar. Morbi ut vestibulum urna, et egestas sapien. Nullam nisi lectus, accumsan tempus vestibulum quis, viverra id urna. Pellentesque eu augue vulputate, rutrum ante commodo, sodales magna. Proin vel lacus et dolor condimentum pretium.<br/>
                Mauris tempus commodo malesuada. Phasellus pretium tempor arcu vitae pulvinar. Pellentesque lobortis posuere ornare. Praesent a faucibus justo. Duis justo sapien, dignissim id erat eu, aliquam auctor ligula. Morbi quis arcu commodo massa varius pellentesque ut quis odio. Vivamus sodales tempus nisl tempor aliquet. Donec sit amet nisl tincidunt lorem tincidunt consectetur ut vel libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor ac velit vel tincidunt. Maecenas consectetur mattis magna nec blandit. Quisque varius dictum hendrerit. Donec interdum quam ullamcorper commodo mollis. Sed et risus iaculis, consectetur eros vitae, varius augue.<br/>
                Donec auctor nibh ut egestas commodo. Nulla ullamcorper massa orci, in laoreet est finibus vitae. Pellentesque sollicitudin quam quis purus varius feugiat. Phasellus in elit non nibh suscipit dictum sed in orci. Sed sapien lectus, interdum eu viverra vel, consequat sed velit. Maecenas sit amet volutpat libero. Etiam et odio leo. Etiam dignissim metus odio, pulvinar pulvinar odio tincidunt ut. Sed tincidunt pulvinar urna ac efficitur. Donec quis tincidunt metus, ut pharetra augue. Donec sed tortor eleifend, eleifend enim lacinia, rutrum arcu. Donec ut feugiat elit, sit amet pellentesque arcu. Vivamus at massa massa. Morbi vitae gravida nulla.<br/>
                Mauris felis arcu, luctus ut viverra ut, pulvinar at felis. Morbi vitae lorem quis leo maximus ullamcorper consequat eu justo. Duis feugiat neque id leo viverra pellentesque. Maecenas efficitur vulputate tellus vel vulputate. Ut ultricies et felis consequat maximus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ligula ex, ultrices iaculis mauris sed, auctor dignissim dui. Duis id sem maximus, feugiat lorem eget, eleifend nulla. Aliquam at velit augue.<br/>
                Praesent ac malesuada dolor. Pellentesque sit amet malesuada orci. Maecenas tortor dolor, euismod nec facilisis nec, tempus ac felis. Donec purus risus, sollicitudin nec mi sed, dignissim dignissim enim. Nunc iaculis rhoncus aliquam. Etiam elementum justo et libero dapibus eleifend. Aenean ut est quis orci vehicula fermentum venenatis at est. Vestibulum urna enim, rhoncus vel cursus sed, condimentum ut nunc. Nulla fermentum nibh id urna ornare ultrices. Pellentesque euismod, sem molestie fermentum scelerisque, ipsum ligula hendrerit arcu, in iaculis libero ligula ac libero. Nam ultrices erat non nisi scelerisque, vitae congue nulla vestibulum. Morbi enim purus, finibus ac elit sit amet, dapibus mattis purus. Nunc feugiat tincidunt vehicula. Aliquam at neque vitae risus vulputate feugiat.
            </div>
        </vue-scrollbar>
    </div>
</template>

<script>
import vueSlider from 'vue-slider-component'
import VueScrollbar from 'vue2-scrollbar'
require("../stylesheets/vue2-scrollbar.css");

export default {

    data: function () {
        return {
            scrollValue: 1,
            duration: 90,
            interval: null,
            playing: false
        }
    },
    components: {
        vueSlider,
        VueScrollbar
    },
    watch: {
        scrollValue: function (val){
            this.update_scroller_position();
        }
    },
    methods:{
        update_scroller_position(){
            let y = (this.$refs.Scrollbar.scrollAreaHeight-this.$refs.Scrollbar.scrollWrapperHeight)/100*this.scrollValue;
            this.$refs.Scrollbar.scrollToY(y)
        }
    },
    mounted: function () {
        this.interval = setInterval(() => {
        this.now = new Date()
        }, 500)
    }

}
</script>

<style scoped>
    .song_viewer{
        margin: auto;
        max-width: 400px;
        max-height: 600px;
    }

    .my-scrollbar{
        width: 300px;
        height: 100%;
        max-height: 450px;
    }

    .song_content{
        width: 280px;
    }

</style>
