export const INIT = 'INIT'
export const SET_LOADED = 'SET_LOADED'
export const UPDATE_JAMSESSION = 'UPDATE_JAMSESSION'
export const UPDATE_JAMSESSION_SONG = 'UPDATE_JAMSESSION_SONG'
export const UPDATE_JAMSESSION_PLAYING = 'UPDATE_JAMSESSION_PLAYING'


export const ADD_MESSAGE = 'ADD_MESSAGE'
