development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chordpromptweb_dev

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chordpromptweb_production
