development:
  clients:
    default:
      database: chordprompt_web_dev
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    use_utc: false
    use_activesupport_time_zone: true

test:
  clients:
    default:
      database: chordprompt_web_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: chordprompt_web_prod
      hosts:
        - localhost:27017
      logger: false

  options:
    raise_not_found_error: false
    use_utc: false
    use_activesupport_time_zone: true
